### ISSUE TITLE
[Bug]: 005-4270 When deleting an account

### ISSUE THREAD

**Issue by Alerymin** [PretendoNetwork/account#102] opened 2024-07-27 17:37 UTC
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

When I try to delete my account, I get error 005-4270 and I cannot delete it

### What did you expect to happen?

I wanted my account to be deleted

### Steps to reproduce?

On 3ds:
1. Open NNID seiings
2. do the process to delete the account
3. when pressing "delete" at the end 005-4270 appears

### Other relevant information. (OPTIONAL)

Done on New 2ds xl, Nimbus version 1.6.1

**Comment by jonbarrow** [comment] 2024-07-27 17:44
`005-XXXX` errors on the 3DS are related to issues with title installation. Iirc trying to delete/remove a network account from a 3DS also triggers a factory reset of the console, so it sounds like something else may be wrong with your console. Though that may only be for unlinking the NNID.

Can you delete a NNID, using Nintendo's servers, normally? If so, would you mind using https://github.com/PretendoNetwork/mitmproxy-nintendo to capture both

- Deleting the NNID on Nintendo's servers
- Trying to delete the PNID using our servers

As 2 separate dump sessions, and then submitting the resulting sessions on our Discord server? That way we can see if anything is wrong on our end, and if so what the expected behavior should be

**Comment by DaniElectra** [comment] 2024-07-27 17:44
IIRC it is currently impossible to delete a Pretendo account from the 3DS as it tries to contact the eShop, which triggers the error you say

**Comment by jonbarrow** [comment] 2024-07-27 17:46
If it's an eShop error then that would likely explain the `005` class error

**Comment by Rathmox** [comment] 2024-07-27 17:50
So the code means eShop cannot be found ? And it would need an eShop server to respond ?

**Comment by jonbarrow** [comment] 2024-12-29 19:59
I'm going to close this for now, since we do not support the eShop servers for various technical reasons thus rendering it impossible to accomplish this. We may explore eShop servers in some capacity in the future so I'll tag this as needing to be revisted

**Closed by jonbarrow** 2024-12-29 19:59 UTC
Labels: bug, awaiting-approval
